// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrmNp4o2r7qG3krIyQicCWyDQvv6YvCP4',
    appId: '1:630989469029:web:37735b98d0f8dd65a6dd8c',
    messagingSenderId: '630989469029',
    projectId: 'authen-hasak',
    authDomain: 'authen-hasak.firebaseapp.com',
    storageBucket: 'authen-hasak.firebasestorage.app',
    measurementId: 'G-BXSW0ZNYPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIO1OJniXnbI8pUoPF82UemAikj9gZbco',
    appId: '1:630989469029:android:fd914cb9f4d0a029a6dd8c',
    messagingSenderId: '630989469029',
    projectId: 'authen-hasak',
    storageBucket: 'authen-hasak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxo4a_EElDBHoS26llQUDWTJyLCbx6gZo',
    appId: '1:630989469029:ios:2798e3a1af045505a6dd8c',
    messagingSenderId: '630989469029',
    projectId: 'authen-hasak',
    storageBucket: 'authen-hasak.firebasestorage.app',
    iosBundleId: 'com.example.authenhasaki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxo4a_EElDBHoS26llQUDWTJyLCbx6gZo',
    appId: '1:630989469029:ios:2798e3a1af045505a6dd8c',
    messagingSenderId: '630989469029',
    projectId: 'authen-hasak',
    storageBucket: 'authen-hasak.firebasestorage.app',
    iosBundleId: 'com.example.authenhasaki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrmNp4o2r7qG3krIyQicCWyDQvv6YvCP4',
    appId: '1:630989469029:web:3d211d9a5604837aa6dd8c',
    messagingSenderId: '630989469029',
    projectId: 'authen-hasak',
    authDomain: 'authen-hasak.firebaseapp.com',
    storageBucket: 'authen-hasak.firebasestorage.app',
    measurementId: 'G-Z2283QNSHG',
  );

}